### PR TITLE
Update henry.py

### PR DESCRIPTION
**Pull request by wanda-carlson**
Test

### CODE REVIEW

**Comment by henry-richard** [comment]
@bert-griffin @sarah-paidpaper please check

**Comment by bert-griffin** [comment]
@henry-richard Sure thing, **Sarah Thompson** please

**Comment by bert-griffin** [comment]
**Test**
_Test_
~Test~
[Test](https://github.com/PaidPaper/public-3/pull/80)
1. Test
2. Test
* Test
* Test
>Test
Test
`Test`
```
Test
Test
```

**Comment by bert-griffin** [comment]
### Test
**Test**
_Test_

> Test

`Test`
[Test](https://github.com/PaidPaper/public-3/pull/79)

1. Test

- Test

- [ ] Test

```
Test
Test
Test
```

**Pull request merged**
