### PR TITLE
Update henry.py

### PR DESCRIPTION
**Pull request by wanda-carlson**

### CODE REVIEW

**Comment by wanda-carlson** [comment]
Test

**Comment by wanda-carlson** [comment]
Test

**Comment by wanda-carlson** [comment]
Test

**Comment by wanda-carlson** [comment]
Test

**Comment by wanda-carlson** [comment]
test

**Review by henry-richard — APPROVED** [review]

**Review by bert-griffin — CHANGES_REQUESTED** [review]
I don't like it

**Review by bert-griffin — APPROVED** [review]

**Pull request merged**
